"use strict";

const eventNames = {
    ROLE_LOGIN : "ROLE_LOGIN",
    ROLE_LOGOUT : "ROLE_LOGOUT",
    ROLE_LOSTCONN : "ROLE_LOSTCONN",
    ROLE_RELOGIN : "ROLE_RELOGIN",
    LEVEL_UP   : "LEVEL_UP",
    STAR_CHANGE : "STAR_CHANGE",
    ADV_LV_CHANGE : "ADV_LV_CHANGE",
    EQUIP_CHANGE : "EQUIP_CHANGE",
    PET_NEW : "PET_NEW",
    PET_SKILL_CHANGE : "PET_SKILL_CHANGE",
    PET_TALENT_CHANGE : "PET_TALENT_CHANGE",
    FLAME_CHANGE : "FLAME_CHANGE",
    PET_MAIN_CHANGE : "PET_MAIN_CHANGE",
    WEAPON_CHANGE : "WEAPON_CHANGE",
    PROP_UPDATED : "PROP_UPDATED",
    PASS_LEVEL : "PASS_LEVEL",
    POWER_CHANGE : "POWER_CHANGE",  //战斗力变化
    VIP_LV_CHANGE : "VIP_LV_CHANGE",   //vip等级变化
    TREASURE_CHANGE : "TREASURE_CHANGE",
};

exports.eventNames = eventNames;