
using UnityEngine;
using UnityEditor;
using UnityEditor.AnimatedValues;
using System;
using System.Collections;
using System.Collections.Generic;


//编辑器图片参考
public class EditorIconWindow : EditorWindow
{
    [MenuItem("Tool/小工具/编辑器图标样式参考")]
    public static void ShowWnd()
    {
        EditorIconWindow wnd = EditorWindow.GetWindow<EditorIconWindow>("编辑器图片参考", true);
        wnd.minSize = new Vector2(300.0f, 400.0f);
        wnd.autoRepaintOnSceneChange = true;
    }
    public Vector2 scrollPosition;
    void OnGUI()
    {
 
        scrollPosition = GUILayout.BeginScrollView(scrollPosition);
 
        //鼠标放在按钮上的样式
        foreach (MouseCursor item in Enum.GetValues(typeof(MouseCursor)))
        {
            GUILayout.Button(Enum.GetName(typeof(MouseCursor), item));
            EditorGUIUtility.AddCursorRect(GUILayoutUtility.GetLastRect(), item);
            GUILayout.Space(10);
        }


        //内置图标
        int lineSize = 20;
        GUILayout.BeginHorizontal();
        for (int i = 0; i < text.Length; ++i)
        {
            if (i > 0 && i % lineSize == 0)
            {
                GUILayout.EndHorizontal();
                GUILayout.BeginHorizontal();
            }
            if (GUILayout.Button(EditorGUIUtility.IconContent(text[i]), GUILayout.Width(50), GUILayout.Height(36)))
                    ShowNotification(new GUIContent(text[i]));                
        }
        GUILayout.EndHorizontal();
        Texture image = EditorGUIUtility.IconContent("console.infoicon").image;
       
        GUILayout.EndScrollView();
    }

    static string []text={"AS Badge Delete",
"AS Badge Move",
"AS Badge New",
"AboutWindow.MainHeader",
"AgeiaLogo",
"Animation.AddEvent",
"Animation.AddKeyframe",
"Animation.EventMarker",
"Animation.NextKey",
"Animation.Play",
"Animation.PrevKey",
"Animation.Record",
"AnimationWrapModeMenu",
"AnimatorController Icon",
"AudioMixerController Icon",
"Avatar Icon",
"AvatarInspector/BodyPartPicker",
"AvatarInspector/BodySIlhouette",
"AvatarInspector/BodySilhouette",
"AvatarInspector/DotFill",
"AvatarInspector/DotFrame",
"AvatarInspector/DotFrameDotted",
"AvatarInspector/DotSelection",
"AvatarInspector/Head",
"AvatarInspector/HeadZoom",
"AvatarInspector/HeadZoomSilhouette",
"AvatarInspector/LeftArm",
"AvatarInspector/LeftFeetIk",
"AvatarInspector/LeftFingers",
"AvatarInspector/LeftFingersIk",
"AvatarInspector/LeftHandZoom",
"AvatarInspector/LeftHandZoomSilhouette",
"AvatarInspector/LeftLeg",
"AvatarInspector/MaskEditor_Root",
"AvatarInspector/RightArm",
"AvatarInspector/RightFeetIk",
"AvatarInspector/RightFingers",
"AvatarInspector/RightFingersIk",
"AvatarInspector/RightHandZoom",
"AvatarInspector/RightHandZoomSilhouette",
"AvatarInspector/RightLeg",
"AvatarInspector/Torso",
"AvatarPivot",
"BuildSettings.Android",
"BuildSettings.Editor",
"BuildSettings.Metro",
"BuildSettings.N3DS",
"BuildSettings.PS3",
"BuildSettings.PS4",
"BuildSettings.PSP2",
"BuildSettings.SamsungTV",
"BuildSettings.SelectedIcon",
"BuildSettings.Standalone",
"BuildSettings.StandaloneGLESEmu",
"BuildSettings.Tizen",
"BuildSettings.Web",
"BuildSettings.Web.Small",
"BuildSettings.WebGL",
"BuildSettings.WebGL.Small",
"BuildSettings.WiiU",
"BuildSettings.XBox360",
"BuildSettings.XboxOne",
"BuildSettings.iPhone",
"BuildSettings.tvOS",
"Camera Icon",
"Clipboard",
"ClothInspector.PaintValue",
"CloudConnect",
"ColorPicker.CycleColor",
"ColorPicker.CycleSlider",
"EditCollider",
"EyeDropper.Large",
"GUISystem/align_horizontally_center",
"GUISystem/align_horizontally_center_active",
"GUISystem/align_horizontally_left",
"GUISystem/align_horizontally_left_active",
"GUISystem/align_horizontally_right",
"GUISystem/align_horizontally_right_active",
"GUISystem/align_vertically_bottom",
"GUISystem/align_vertically_bottom_active",
"GUISystem/align_vertically_center",
"GUISystem/align_vertically_center_active",
"GUISystem/align_vertically_top",
"GUISystem/align_vertically_top_active",
"GameObject Icon",
"HorizontalSplit",
"Icon Dropdown",
"MeshRenderer Icon",
"Mirror",
"MonoLogo",
"MoveTool On",
"MoveTool",
"PauseButton Anim",
"PauseButton On",
"PauseButton",
"PlayButton Anim",
"PlayButton On",
"PlayButton",
"PlayButtonProfile Anim",
"PlayButtonProfile On",
"PlayButtonProfile",
"PreMatCube",
"PreMatCylinder",
"PreMatLight0",
"PreMatLight1",
"PreMatQuad",
"PreMatSphere",
"PreMatTorus",
"PreTextureAlpha",
"PreTextureMipMapHigh",
"PreTextureMipMapLow",
"PreTextureRGB",
"Prefab Icon",
"PrefabModel Icon",
"PrefabNormal Icon",
"Profiler.NextFrame",
"Profiler.PrevFrame",
"Profiler.Record",
"RectTool On",
"RectTool",
"RectTransformBlueprint",
"RectTransformRaw",
"RotateTool On",
"RotateTool",
"ScaleTool On",
"ScaleTool",
"SceneviewAudio",
"SceneviewFx",
"SceneviewLighting",
"ScriptableObject Icon",
"Search",
"SettingsIcon",
"Shader Icon",
"SocialNetworks.FacebookShare",
"SocialNetworks.LinkedInShare",
"SocialNetworks.Tweet",
"SocialNetworks.UDNLogo",
"SocialNetworks.UDNOpen",
"SpeedScale",
"Sprite Icon",
"StepButton Anim",
"StepButton On",
"StepButton",
"Terrain Icon",
"TerrainInspector.TerrainToolPlants",
"TerrainInspector.TerrainToolRaise",
"TerrainInspector.TerrainToolSetHeight",
"TerrainInspector.TerrainToolSettings",
"TerrainInspector.TerrainToolSmoothHeight",
"TerrainInspector.TerrainToolSplat",
"TerrainInspector.TerrainToolTrees",
"TestFailed",
"TestIgnored",
"TestInconclusive",
"TestNormal",
"TestPassed",
"TextAsset Icon",
"Toolbar Minus",
"Toolbar Plus More",
"Toolbar Plus",
"TreeEditor.AddBranches",
"TreeEditor.AddLeaves",
"TreeEditor.BranchFreeHand",
"TreeEditor.BranchRotate",
"TreeEditor.BranchTranslate",
"TreeEditor.Duplicate",
"TreeEditor.LeafRotate",
"TreeEditor.LeafTranslate",
"TreeEditor.Refresh",
"TreeEditor.Trash",
"UnityLogo",
"VerticalSplit",
"ViewToolMove On",
"ViewToolMove",
"ViewToolOrbit On",
"ViewToolOrbit",
"ViewToolZoom On",
"ViewToolZoom",
"WaitSpin00",
"WaitSpin01",
"WaitSpin02",
"WaitSpin03",
"WaitSpin04",
"WaitSpin05",
"WaitSpin06",
"WaitSpin07",
"WaitSpin08",
"WaitSpin09",
"WaitSpin10",
"WaitSpin11",
"WelcomeScreen.AssetStoreLogo",
"WelcomeScreen.MainHeader",
"WelcomeScreen.UnityAnswersLogo",
"WelcomeScreen.UnityBasicsLogo",
"WelcomeScreen.UnityForumLogo",
"WelcomeScreen.VideoTutLogo",
"animationvisibilitytoggleoff",
"animationvisibilitytoggleon",
"blendKey",
"boo Script Icon",
"console.erroricon",
"console.erroricon.sml",
"console.infoicon",
"console.warnicon",
"cs Script Icon",
"editicon.sml",
"js Script Icon",
"lightMeter/greenLight",
"lightMeter/lightRim",
"lightMeter/orangeLight",
"lightMeter/redLight",
"playLoopOff",
"preAudioAutoPlayOff",
"preAudioAutoPlayOn",
"preAudioLoopOff",
"preAudioLoopOn",
"preAudioPlayOff",
"preAudioPlayOn",
"renderdoc",
"sv_icon_dot0_pix16_gizmo",
"sv_icon_dot0_sml",
"sv_icon_dot10_pix16_gizmo",
"sv_icon_dot10_sml",
"sv_icon_dot11_pix16_gizmo",
"sv_icon_dot11_sml",
"sv_icon_dot12_pix16_gizmo",
"sv_icon_dot12_sml",
"sv_icon_dot13_pix16_gizmo",
"sv_icon_dot13_sml",
"sv_icon_dot14_pix16_gizmo",
"sv_icon_dot14_sml",
"sv_icon_dot15_pix16_gizmo",
"sv_icon_dot15_sml",
"sv_icon_dot1_pix16_gizmo",
"sv_icon_dot1_sml",
"sv_icon_dot2_pix16_gizmo",
"sv_icon_dot2_sml",
"sv_icon_dot3_pix16_gizmo",
"sv_icon_dot3_sml",
"sv_icon_dot4_pix16_gizmo",
"sv_icon_dot4_sml",
"sv_icon_dot5_pix16_gizmo",
"sv_icon_dot5_sml",
"sv_icon_dot6_pix16_gizmo",
"sv_icon_dot6_sml",
"sv_icon_dot7_pix16_gizmo",
"sv_icon_dot7_sml",
"sv_icon_dot8_pix16_gizmo",
"sv_icon_dot8_sml",
"sv_icon_dot9_pix16_gizmo",
"sv_icon_dot9_sml",
"sv_icon_name0",
"sv_icon_name1",
"sv_icon_name2",
"sv_icon_name3",
"sv_icon_name4",
"sv_icon_name5",
"sv_icon_name6",
"sv_icon_name7",
"sv_icon_none",
"sv_label_0",
"sv_label_1",
"sv_label_2",
"sv_label_3",
"sv_label_4",
"sv_label_5",
"sv_label_6",
"sv_label_7",
"tree_icon",
"tree_icon_branch",
"tree_icon_branch_frond",
"tree_icon_frond",
"tree_icon_leaf"};
}